# Copyright 2019 Google, LLC.
#

name: GCloud

on:
  workflow_dispatch:
    inputs:
      PROJECT_ID:
        description: 'Project ID'
        required: True

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: helloworld-nodejs

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: 'ai-people-362119'
        export_default_credentials: true
        
        #credentials_json: '${{ secrets.RUN_SA_KEY }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # Build and push image to Google Container Registry
    - name: List
      run: |-
        gcloud projects list
