# Copyright 2019 Google, LLC.
#

name: Network Onboarding validation

on:
  workflow_dispatch:
    inputs:
      PROJECT_ID:
        description: 'Project ID'
        required: True



jobs:
  setup-build-deploy:
    name: On-Boarding Validations
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      # Build and push image to Google Container Registry
      - name: Validating project information
        run: |-
          result=$(gcloud projects list | grep ${{ github.event.inputs.PROJECT_ID }})
          if [[ -z $result ]] 
          then
            echo "Project exist"
          else
            echo "Project doesn't exist"
          fi
