# Copyright 2019 Google, LLC.
#

name: Network Onboarding validation

on:
  workflow_dispatch:
    inputs:
      PROJECT_ID:
        description: 'Project ID'
        required: True



jobs:
  setup:
    name: On-Boarding Validations
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      # Build and push image to Google Container Registry
      - name: Validating project information
        continue-on-error: true
        run: |-
          project_number=$(gcloud projects list | grep ${{ github.event.inputs.PROJECT_ID }} | awk '{print $3}' | sed -n '1!p')
          
          if [[ -z $project_number ]] 
          then
            echo "::error::The project number is invalid!"
          fi
        
